### ISSUE TITLE
connect失败

### ISSUE THREAD

**Issue by zhaoxiaoqian666** [cm-jsw/GraphCut#1]
这个真的可以运行出结果吗，为什么总是connect失败

**Comment by zhaoxiaoqian666** [comment]
NEWCutUI 为什么并没有用？

**Comment by sdfghjkyuio** [comment]
我也想问QAQ

**Comment by ifelse97** [comment]
请问pymaxflow在哪找啊

**Comment by sdfghjkyuio** [comment]
> 请问pymaxflow在哪找啊

直接pip install安装不了吗？

**Comment by xuexiaozhong** [comment]
> 请问pymaxflow在哪找啊

https://www.lfd.uci.edu/~gohlke/pythonlibs/
找到对应版本，保存到一个路径
然后 pip install 这个路径

**Comment by SkySailing** [comment]
have the same problem!

> Traceback (most recent call last):
>   File "/GraphCut-master2/GraphCut-master2/NewCutUI.py", line 161, in <module>
>     newUI = NewCutUI()
>   File "/GraphCut-master2/GraphCut-master2/NewCutUI.py", line 25, in __init__
>     openButton.triggered.connect(self.on_open)
> TypeError: connect() failed between triggered(bool) and on_open()
